featureName=todos
serenity.browser.maximized = true
current.target.version = sprint-1
report.assets.directory = ${user.dir}/src/test/resources/assets
chrome.switches=--remote-allow-origins=*,--disable-password-manager,--disable-save-password-bubble,--disable-features=PasswordManagerEnabled,PasswordCheck

webdriver.driver=chrome
webdriver.autodownload = true

webdriver.driver=chrome
webdriver.autodownload=true
serenity.browser.maximized=true

