name: Main Workflow
on: [workflow_dispatch]

jobs:
  build:
    name: Run k6 test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Install k6 and k6-reporter
        run: |
          sudo apt-get update
          sudo apt-get install -y gnupg2
          curl -s https://dl.k6.io/key.gpg | sudo apt-key add -
          echo "deb https://dl.k6.io/deb stable main" | sudo tee /etc/apt/sources.list.d/k6.list
          sudo apt-get update
          sudo apt-get install -y k6
          sudo npm install -g k6-reporter
          
      - name: Run k6 tests and generate HTML report
        env:
          K6_CLOUD_TOKEN: ${{ secrets.K6_CLOUD_TOKEN }}  # Si usas k6 cloud
          K6_COMMAND: ${{ inputs.cloud == 'true' && echo 'cloud' || echo 'run' }}
          K6_JSON_OUTPUT: "load-test-summary.json"
          K6_HTML_REPORT: "load-test-report.html"
        run: |
          # Ejecuta el comando k6 y asegura que el reporte se genere incluso si k6 falla
          sh -c "k6 run performance/deeplink.js --summary-export=$K6_JSON_OUTPUT" || true

          # Genera el reporte HTML usando k6-reporter
          k6-reporter $K6_JSON_OUTPUT $K6_HTML_REPORT

          # Imprime la ubicación del reporte
          echo "Report generated at $K6_HTML_REPORT"
          
      - name: Upload performance test results (HTML)
        uses: actions/upload-artifact@v4
        with:
          name: k6-report-html
          path: load-test-report.html

      - name: Upload performance test results (JSON)
        uses: actions/upload-artifact@v4
        with:
          name: k6-report-json
          path: load-test-summary.json
